const users = ["Juanita Anthony", "Melva Alford", "Ana Giles", "Christensen Rowe", "Debora Floyd", "Margret Meadows", "Rosales Roman", "Tanisha Quinn", "Millie Dotson", "Donaldson Bird", "Rosa Vazquez", "Mcconnell Dickerson", "Chandra Rivas", "Miranda Chandler", "Cooke Garrett", "Hickman Jackson", "Pacheco Mcneil", "Lourdes Caldwell", "Mueller Wilkins", "Francine Mccarthy", "Gail Sandoval", "Chen Wells", "Janie Bailey", "Kasey Mccarty", "Gabrielle Mcguire", "Cole Nieves", "Marla Chapman", "Branch Hoffman", "Claudia Rich", "Gonzales Chaney", "Flores Grant", "Lewis Montoya", "Clarke Acosta", "Susanna Collins", "Small Reeves", "Connie Santiago", "Carmella Maxwell", "Knox Beck", "Sanchez Mcconnell", "Duffy Silva", "Ilene Dunn", "Elise Cooley", "Gomez Acevedo", "Tisha Ashley", "Susanne Gray", "Nanette Vaughan", "Nona Lott", "Lois Baxter", "Watson Parks", "Nash Weeks", "Whitney Hodges", "Rosa White", "Ferguson Schwartz", "Patrice Atkins", "Victoria Pena", "Mildred Terry", "Donovan Nicholson", "Corrine Morin", "Daugherty Baird", "Bartlett Mccoy", "Henry Baker", "Houston Guerrero", "Young Sosa", "Oneil Savage", "Trisha Nichols", "Susie Atkinson", "Kellie Kramer", "Andrea Duffy", "Knight Ray", "Santana Bradley", "Perkins Calderon", "Maureen Durham", "Leblanc Harrison", "Roach Blanchard", "Sherman Branch", "Simone Cameron", "Hall Lynn", "Dawn Romero", "Zelma Tillman", "Walton Noble", "Tonya Dillard", "Katelyn Jones", "Cooper Dennis", "Kathy Rosario", "Ebony Moran", "Estela Shepherd", "Davis Robinson", "Powell Jacobs", "Fletcher Simmons", "Jeri Adams", "Billie Tran", "Schroeder Raymond", "Charmaine Cunningham", "Jeannie Clarke", "Tameka Mendez", "Campos Newman", "Rae Mcmahon", "Vazquez Holman", "Nicholson Thomas", "Hahn Gallegos", "Rollins Welch", "Dionne Reynolds", "Tucker Mckay", "Shannon Brooks", "Georgette Barker", "Eloise Buckner", "Beulah Carpenter", "Howe Solis", "Thelma Montgomery", "Bishop Hall", "Lori Olsen", "Ellis Andrews", "Charity Norman", "Roberts Downs", "Eunice Rollins", "Karen Wilkinson", "Polly Buchanan", "Coleman Wise", "Greer Allen", "Geraldine Schultz"]

users.forEach((item) => {
    const elItem = document.createElement('li');

    elItem.textContent = item
    document.body.append(elItem);
    elItem.style.listStyle = 'none';
    elItem.style.lineHeight = '30px';
})